# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Prueba_iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'AFNetworking'
  pod 'RealmSwift'
  post_install do |installer|
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['SWIFT_VERSION'] = '4.0'
          end
      end
  end

  # Pods for Prueba_iOS

  target 'Prueba_iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Prueba_iOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
